### ISSUE TITLE
[doc] ETQ dev je souhaite avoir une documentation 'dev' sur la définition et l'utilisation des tokens et variables d'environnement

### ISSUE THREAD

**Issue by ymansiaux** [ThinkR-open/lozen#1]
ETQ dev, j'aimerais avoir tout les token fonctionnels et avoir une documentation sur leur utilisation de manière à ce que .les développeurs ne ratent plus, ou de manière consciente, de faire passer les tests unitaires

## Client - Validation 

+ [x] Un autre dev de ThinkR arrive à set up l'environnement nécessaire pour lancer tout les tests unitaire de {lozen}

## Dev - Tech

+ [x] Supprimer le README dans `dev`
+ [x] Dans le README, faire une section **As user** et une section **As developer**
+ [x] Dans la section **As user**, spécifier la tête qui doit avoir le fichier .Renviron et dire qu'on peut l'éditer avec `usethis::edit_r_environ()`

````
POUET="pouet"
POUET="pouet"
POUET="pouet"
````
+ [x] Dans la section **As developer**, spécifier la tête qui doit avoir le fichier .Renviron et dire qu'on peut l'éditer avec `usethis::edit_r_environ()`

````
POUET="pouet"
POUET="pouet"
POUET="pouet"
````

+ [x] Ajouter la variable `CONNECT_NAME` dans le fichier .Renviron des développeurs (leur dire d'utiliser `rsconnect::accounts()$server` pour connaître les possibilités)
+ [x] Renommer la variable `ALLOW_... `avec `ALLOW_..._TO_DEPLOY_ON_CONNECT` et effectuer les modifs nécessaires dans le code
+ [x] Remplacer dans les paramètres de fonctions nécessaires `connect_name = "connect"` par `connect_name = Sys.getenv("CONNECT_NAME", unset = "connect")` + `rsconnect::aplications(server = connect_name)` à l'intérieur des fonctions en question

+ [x] Préciser la scope du github pat : github pat scope: admin:org, delete_repo, project, repo, user, workflow

+ [x] Ajouter User must connect their connect account manually within Rstudio

+ [x] Pour les tests : Il faut avoir déjà déployé au moins 1 contenu depuis le Rstudio duquel est lancé le test

+ [x] Rajouter la variable d'environnement CONNECT_NAME != "" dans les tests  et modifier rsconnect::applications(server = Sys.getenv("CONNECT_NAME")

**Comment by ymansiaux** [comment]
@MargotBr à faire tester par @ALanguillaume  à l'occasion :)

**Comment by ymansiaux** [comment]
@MargotBr pour info, test prévu avec @ALanguillaume le 02/06

**Comment by ymansiaux** [comment]
@ALanguillaume les manques relevés ce matin ont été corrigés.
Si tu peux refaire un check complet à partir de main stp

**Comment by ymansiaux** [comment]
@ALanguillaume au vu du succès du devtools::test(), peut on fermer ce ticket ?

**Comment by ALanguillaume** [comment]
Je viens de pull main et de relancer les tests sur une session vierge. Je te dis ce qu'il en est.

**Comment by ALanguillaume** [comment]
C'est bon pour moi
```
══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 2206.8 s

── Skipped tests  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• empty test (16)

[ FAIL 0 | WARN 0 | SKIP 16 | PASS 219 ]
```
