### ISSUE TITLE
ETQ leadev, j'aimerai des fonctions extra simplifiées pour commencer mes projets

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/lozen#60]
## Validation

- [ ] Une fonction générique (par exemple `lozen::new_project_all(config = "config.yaml")`) peut prendre un fichier de configuration de type YAML en entrée dans lequel on peut spécifier nos options personnelles. Par défaut, il contient les options pour ThinkR et permet de générer toutes les fonctions de démarrage de projet avec {lozen}.
Ainsi:  
    - [ ] Je peux créer un nouveau projet, synchronisé sur GitLab au format R package, avec le CI en place et fonctionnel, le dépôt GitLab et la totalité de ses modalités recommandées par ThinkR avec `lozen::new_project_all(config = "config_gitlab_pkg.yaml")`
    - [ ] Je peux modifier le contenu de ce projet avec toutes les autres fonctions de {lozen} en complément, si je le souhaite, après avoir cloné en local manuellement mon projet.
    - [ ] Je peux faire de même avec golem+gitlab
    - [ ] Il existe aussi une version permettant de déployer l'app Shiny du golem sur Connect `lozen::new_project_all(config = "config_gitlab_golem_connect.yaml")`
    - [ ] Je peux faire de même avec le book
    - [ ] (facultatif) Il existe aussi une version permettant de déployer le book en version master/prod du book sur Connect
    - [ ] Ces fonctions existent aussi avec leur variantes GitHub
    - [ ] Potentiellement des alias existent pour des versions qui utiliseraient les templates par defaut ThinkR. Par exemple un alias pour `lozen::new_project_all(config = "config_gitlab_pkg.yaml")` pourrait être `lozen::new_project_gitlab_pkg()`. Il contient aussi la possibilité de mettre un fichier de config complémentaire

## Dev

- Le fichier de config pourrait contenir les différents paramètres suivants. Chaque utilisateur peut utiliser son propre fichier de configuration à chaque nouveau projet

```yaml
forge: gitlab # or github
forge_url: https://gitlab.com
gitlab_token: GITLAB_TOKEN
project_type: package # or book, golem
name_licence: Bob
# ... # Everything needed to start
```

- [x] Un fichier de config général qui contient tout est dispo dans "inst/"
- [ ] La fonction `new_project_all()` permet de gérer:
    - [x] gitlab + pkg + ci check/pkgdown
    - [x] gitlab + book + ci master/prod html sur pages
    - [x] gitlab + golem + ci check/pkgdown
    - [ ] gitlab + golem + ci check/pkgdown + app sur connect
    - [ ] github + pkg + ci check/pkgdown
    - [ ] github + book + ci master/prod html sur pages
    - [ ] github + golem + ci check/pkgdown
    - [ ] github + golem + ci check/pkgdown + app sur connect
- [ ] Un fichier de config pour les différentes variantes: gitlab/github + pkg/golem/book

**Comment by dagousket** [comment]
## Pour la partie GitHub (étapes de la vignettes `ab - Create a new project with GitHub`)

-> wip de la branche `https://github.com/ThinkR-open/lozen/tree/60-all-in-one-gh`

🟢 - fonctionnel + automatisé
🟣 - fonctionnel + manuel mais pas automatisable
🟠 - fonctionnel + manuel mais automatisable
🔴 - non fonctionnel
🟡 - en cours

- [ ] ~~Packages~~
- 🟢  Define the name of the principal branch
- 🟢 Connexion to GitHub
- 🟠 Create a new project or use an existing project
    - nécessite d'avoir crée le dossier en local (cf. fusen), ordre à changer pour automatiser 
- [ ] Manipulate your project and add everything needed
        -   🟢 Define local installation and clone
        -   🟡   Create R project skeleton
            -  🟢 package
            -  golem
            -  book
        -     Create weekly
           - ancien ou nouveau board ? (2 fonctions de lozen specifiques, fonctionnelles), a specifier dans la config
        -     Manage a calendar (pas pertinent ici)
        -  🟢 Add commit templates (message au dev à visibiliser)
        -  🟢 Add issue templates
        -  🟢 Add CI log check for Code coverage
        -   🟢   Push to server
        -    🟢  Start main and create a production branch 
- 🔴  Protect branches -> fonction pour gitlab a faire en manuel sur github
- 🔴  No autoclose issue and coverage regex ->  fonction pour gitlab a faire en manuel sur github, coverage regex non pertinent pour github
- 🟡  Create the board
      -  nouvelle version seulement (graphql)
      -  deux types de boards : orga ou user (ajouter un message d'erreur pertinent si node id pas trouvé)
   - 🟡  creer le board
   - 🟠   creer les colonnes -> a faire avec graphql
- 🟠  Create the wiki pages -> faire le home à la main, à automatiser si possible
-  Add some special issues in the board 
    - 🟢 ajouter les issues au repo
    - lier les issues au projet (nécessite d'avoir créer le colonnes du projet)
