### ISSUE TITLE
 ETQ leadev, j'aimerai des fonctions extra simplifiées pour commencer un package sur GitHub

### ISSUE THREAD

**Issue by dagousket** [ThinkR-open/lozen#64]
**Sous-partie de l'issue #60**

## Validation

- [x] l'appel à la fonction`init_project_with_all()` avec un fichier de config spécifique aux options github pour un **package** crée un repo github avec l'ensemble des étapes de la vignette de lozen _ab - Create a new project with GitHub_  :

   - [x] un fichier de config de test pour github est disponible

-> https://github.com/ThinkR-open/lozen/blob/main/inst/thinkr_config_test_amend_github.yml

![image](https://github.com/ThinkR-open/lozen/assets/54443785/2413660c-ddb4-446d-b154-d8929073bfde)

   - [x] la fonction previent que certaines étapes seront à réaliser manuellement

![Screenshot 2023-08-17 at 16 56 29](https://github.com/ThinkR-open/lozen/assets/54443785/c6931203-5392-49ac-8824-34524f47769c)

   - [x] la fonction demande confirmation à l'utilisateur pour passer à l'étape suivante lorsque l'étape précédente est manuelle

![image](https://github.com/ThinkR-open/lozen/assets/54443785/c4233ea9-6d18-4e6d-9fff-738e5f92e594)

![image](https://github.com/ThinkR-open/lozen/assets/54443785/930dd5b4-dc07-4ff2-9e6c-29363d13c2e8)

![image](https://github.com/ThinkR-open/lozen/assets/54443785/7bc97f94-3b68-4941-a591-c208fe9b28b2)

![image](https://github.com/ThinkR-open/lozen/assets/54443785/01ae9940-015c-457e-83bf-c12e7680d63c)

   - [x] le repo créé pou un **user** contient tout les éléments attendus :
   - [x] un repo 

<img width="1347" alt="image" src="https://github.com/ThinkR-open/lozen/assets/54443785/d13fef52-6572-4258-8ba3-dc03b30d7d66">

   - [x] CI au vert

<img width="1350" alt="image" src="https://github.com/ThinkR-open/lozen/assets/54443785/5ec71541-60cb-4d4a-bcb4-4d1d1b20d9c8">

   -  [x] template issue

<img width="1297" alt="image" src="https://github.com/ThinkR-open/lozen/assets/54443785/bf7a9f17-3eda-4c56-9c0a-8fe559d0f4f8">

   - [x] template MR

<img width="795" alt="Screenshot 2023-08-17 at 16 25 26" src="https://github.com/ThinkR-open/lozen/assets/54443785/11db6ebb-bad0-434d-9e46-8c7774270c24">

   - [x] premières issues

<img width="982" alt="image" src="https://github.com/ThinkR-open/lozen/assets/54443785/3dddd683-ab9d-4baf-bf46-12acf1144f83">

   - [x] board

<img width="1204" alt="image" src="https://github.com/ThinkR-open/lozen/assets/54443785/96d4ec69-b34c-42fc-840f-a866dea34a93">

- [x] le repo créé pour une **organization** est aussi fonctionnel

-> https://github.com/ThinkR-open/testinitalllozen

> ce repo et son project peuvent etre supprimé une fois l'issue validée

- [x] la liste des étapes ayant le potentiel d'être automatisées/ameliorées est documentée dans une nouvelle issue

-> https://github.com/ThinkR-open/lozen/issues/66

### Etape de la vignette _ab - Create a new project with GitHub)_ à réaliser

🟢 - fonctionnel + automatisé
🟣 - fonctionnel + manuel mais pas automatisable
🟠 - fonctionnel + manuel mais automatisable
🔴 - non fonctionnel
🟡 - en cours
⚪ - todo

- Packages -> pas pertinent dans la vignette
- 🟢  Define the name of the principal branch
- 🟢 Connexion to GitHub
- 🟠 Create a new project or use an existing project
   - nécessite d'avoir crée le dossier en local (cf. fusen), ordre à changer pour automatiser 
- 🟢   Manipulate your project and add everything needed
   - 🟢 Define local installation and clone
   - 🟢 Create R project skeleton
      -  🟢  package
         - -> `usethis::with_project(project_name, {usethis::use_r("start")})` pour le que CI de coverage passe 
   - 🔴  Create weekly
      - -> ancien ou nouveau board ? (2 fonctions de lozen specifiques, fonctionnelles), a specifier dans la config
      - `system.file("doc", "ae-create-weekly-with-github-or-gitlab.Rmd", package = "lozen")` retourne `NULL`
   - Manage a calendar (pas pertinent ici)
   - 🟢 Add commit templates (message au dev à visibiliser)
   - 🟢 Add issue templates
   - 🟢 Add CI log check for Code coverage
   - 🟢 Push to server
   - 🟢 Start main and create a production branch 
- 🔴 Protect branches -> fonction pour gitlab a faire en manuel sur github (message avec lien)
- 🔴 No autoclose issue and coverage regex ->  fonction pour gitlab a faire en manuel sur github, coverage regex non pertinent pour github
- 🟠  Create the board
   - nouvelle version seulement (graphql)
   - deux types de boards : orga ou user (ajouter un message d'erreur pertinent si node id pas trouvé)
   - 🟢   creer le board
   - 🟠   creer les colonnes -> a faire avec graphql
- 🟠  Create the wiki pages -> faire le home à la main, à automatiser si possible
-  🟠 Add some special issues in the board 
    - 🟢 ajouter les issues au repo
    - 🟠   lier les issues au projet -> (nécessite d'avoir créer le colonnes du projet)

**Comment by statnmap** [comment]
Parfait ! Testé et fonctionnel sur geronimo:  https://github.com/statnmap/newprojectpkg
