### ISSUE TITLE
ETQ dev je souhaite une montée de version de lozen et un NEWS à jour

### ISSUE THREAD

**Issue by dagousket** [ThinkR-open/lozen#67]
## Validation

- [x]  le fichier DESCRIPTION est mis à jour

![image](https://github.com/ThinkR-open/lozen/assets/54443785/78bb6631-a70f-4b0f-9ac2-ca6a84f59906)

-> https://github.com/ThinkR-open/lozen/blob/main/DESCRIPTION

- [x]  le fichier NEWS et mis à jour

![image](https://github.com/ThinkR-open/lozen/assets/54443785/db301c88-be98-4c2d-9c0d-7314a230034a)

-> https://github.com/ThinkR-open/lozen/blob/main/NEWS.md

## Dev

- utiliser un titre "Development" plutot que d'utiliser chaque version de dev dans news

**Comment by statnmap** [comment]
Merci.
Pour info, soit tu mets un numéro de version, soit tu mets (Development).  
Je corrige. J'en profite pour avoir une vraie version stable taguée en 1.3.0.
